pipeline {

    agent {
        docker {
            image: 'node18-alpine'
            reuseNode:
        }
    }

    stages {
        stage('Build') {
            steps {
                sh '''
                node --version

                npm ci
                npm run build

                ls -la
                '''
            }
        
            post {
                always {
                    echo "Test stage done!"
                }
            }
        }
    }
} 
